#!/bin/bash

echo "Checking Google APIs status for project misha-project-469120..."
echo ""
echo "Please enable these APIs by clicking the links:"
echo ""
echo "1. Google Sheets API:"
echo "   https://console.cloud.google.com/apis/library/sheets.googleapis.com?project=misha-project-469120"
echo ""
echo "2. Google Drive API:"
echo "   https://console.cloud.google.com/apis/library/drive.googleapis.com?project=misha-project-469120"
echo ""
echo "After enabling both APIs, wait about 30 seconds for them to activate."
echo ""
echo "Common issues:"
echo "- Error 403: APIs not enabled yet"
echo "- Make sure you're logged into the correct Google account"
echo "- The service account email is: qr-scanner@misha-project-469120.iam.gserviceaccount.com"