#!/bin/bash

echo "Steps to create a new service account:"
echo ""
echo "1. Go to: https://console.cloud.google.com/iam-admin/serviceaccounts/create?project=misha-project-469120"
echo ""
echo "2. Create service account:"
echo "   - Name: qr-scanner-v2"
echo "   - ID: qr-scanner-v2"
echo "   - Click CREATE AND CONTINUE"
echo ""
echo "3. Grant role:"
echo "   - Select: Basic → Editor"
echo "   - Click CONTINUE"
echo "   - Click DONE"
echo ""
echo "4. Create key:"
echo "   - Click on the new service account (qr-scanner-v2@misha-project-469120.iam.gserviceaccount.com)"
echo "   - Go to KEYS tab"
echo "   - ADD KEY → Create new key → JSON"
echo "   - Save as credentials_v2.json"
echo ""
echo "5. Test with: mv credentials.json credentials_old.json && mv credentials_v2.json credentials.json"
echo "6. Run: go run test_api.go"